### ISSUE TITLE
현재 N동에 등록되어 있는 음식점이 둘다 S 동임.

### ISSUE THREAD

**Issue by topjung3** [techinpark/Pangyo-FGP#3]
S 로만 바꾸면 될 듯.

**Comment by techinpark** [comment]
@topjung3 좋은 의견 감사드립니다

**Comment by techinpark** [comment]
@all-contributors please add @topjung3 for doc

**Comment by techinpark** [comment]
@all-contributors please add @topjung3 for doc

**Comment by techinpark** [comment]
@all-contributors please add @techinpark for doc
